all: # 全局组(默认) # https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#id18
  children:
    tencent: # 自定义组名
      vars:
        ansible_host: localhost
        ansible_port: 22
        ansible_root_user: root
        ansible_root_password: Jiang
      hosts:
        tc.bai-su-root:
          ansible_user: bai
          ansible_password: Jiang
          ansible_become: true
          ansible_become_method: su
          ansible_become_user: "{{ ansible_root_user }}"
          ansible_become_password: "{{ ansible_root_password }}"
        tc.ansible_user_01:
          ansible_user: ansible_user_01
          ansible_password: passwd
        tc.root:
          ansible_user: "{{ ansible_root_user }}"
          ansible_password: "{{ ansible_root_password }}"
          # - General for all connections:
          # ansible_connection: ssh # paramiko # smart # ssh,
          # - Specific to the SSH connection
          # ansible_ssh_private_key_file:
          # ansible_ssh_common_args: -o ControlMaster=auto -o ControlPersist=5s -o ControlPath=/Users/bai/Coding/Projects/BaiJiangJie/ansible/main/tmp/%h-%r # ProxyCommand
          # ansible_sftp_extra_args:
          # ansible_scp_extra_args:
          # ansible_ssh_extra_args: -o ControlMaster=no
          # ansible_ssh_pipelining:
          # ansible_ssh_executable:
          # - Privilege escalation (see Ansible Privilege Escalation for further details)
          # ansible_become: true
          # ansible_become_method: sudo
          # ansible_become_user: root
          # ansible_become_password: Jiang
          # ansible_become_exe:
          # ansible_become_flags:
          # - Remote host environment parameters
          # ansible_shell_type:
          # ansible_python_interpreter:
          # ansible_shell_executable:

